nameContains: # What words should be listened for?
  - 'banned'
  - 'word'
commands: # The commands that should be ran upon seeing a player join with a name containing the above ({player} is for the player name)
  - 'kick {player} banned name!' #

ignoreCase: true # Should the case nameContains be case sensitive or no